# Dependencies
rogue:            true

# Permalinks
permalink:        pretty

# Setup
title:            Calum Shepherd
tagline:          Product Lead & IC | Building Data-Driven Products
url:              https://calumshepherd.com
paginate:         4
baseurl:          /
author:
  name:           Calum Shepherd
  url:            https://x.com/calumshepherd
  email:

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Menu
pages_list:
  speaking: '/speaking'
  about: '/about'
  posts: '/posts'
# Sitemaps
plugins:
  - jekyll-sitemap
  - jekyll-paginate
